### ISSUE TITLE
Any ideas on to make it more nice?

### ISSUE THREAD

**Issue by basiirzulkifle** [basiirzulkifle/calculator-js#2]
Help to give me some suggestion which CSS framework is good to try out now? I do feel like to explore React

**Comment by hamiruldev** [comment]
@basiirzulkifle 

I been coding almost 10 years. the best advice gave by my senior that help me along my career path is react + MUI + next.js + Nodejs

**Comment by basiirzulkifle** [comment]
Thank you @hamiruldev !
